### ISSUE TITLE
Padding oracle attack in PBESScheme

### ISSUE THREAD

**Issue by afk11** [sop/crypto-util#1]
I came across your library as I happened to be working on something similar. I noticed the PBESScheme file has a function `_removePadding` which is called after a successful decryption occurs: 

https://github.com/sop/crypto-util/blob/master/lib/CryptoUtil/PBE/PBES2.php#L110
https://github.com/sop/crypto-util/blob/master/lib/CryptoUtil/PBE/PBEScheme.php#L98

I am not an expert on the topic, but I notice that if you reveal the nature of the exception to an attacker, he can distinguish the cases where he provided bad cipher text, and where the provided ciphertext was valid but didn't have the correct padding. More info: http://robertheaton.com/2013/07/29/padding-oracle-attack/

As I understand it, the information leak is what introduces the problem, so the fix might be simply to catch all exceptions during `decryptWithKey`, and throw another which simply states the operation failed?

**Comment by sop** [comment]
Thank you for the feedback!

While i agree with you, i think it's responsibility of the application developer to deal with information leak. End users should not get to see error messages from the libraries.

Nevertheless i fixed the issue by generalizing the exception message for failed decryption operation, but chaining the original exception as well. This should be sufficent in case library exceptions end up in GUI.

**Comment by paragonie-scott** [comment]
> While i agree with you, i think it's responsibility of the application developer to deal with information leak. End users should not get to see error messages from the libraries.

Have you perchance seen [error-prone cryptographic designs](https://cr.yp.to/talks/2015.01.07/slides-djb-20150107-a4.pdf) (PDF) before? Highly recommended slide deck (I wish I could find a video of the talk that accompanies it. It was a presentation at NIST that was live-streamed.)

The more general problem here isn't the padding oracle, it's that chosen-ciphertext attacks are even possible. It would be a good idea to mitigate CCAs in your cryptography features. See: [Using encryption and authentication correctly](https://paragonie.com/blog/2015/05/using-encryption-and-authentication-correctly).

**Comment by afk11** [comment]
Thanks for fixing quickly @sop, and @paragonie-scott for clarifying the nature of the problem. 

I just checked through RFC 2898, it documents a MAC procedure at least. Not sure how well AEAD ciphers associated data would be handled in schemes such as in PKCS8 though at least there's something!

**Comment by sop** [comment]
Far as i understand, the MAC verification defined by [RFC 2898](https://tools.ietf.org/html/rfc2898#section-7) is just another scheme, and is not directly employed by PBE. That is, PBES2 for example cannot have authentication embedded into decrypt operation. Therefore providing integrity is left for the underlying cipher algorithm, and i don't know how well this is supported.
I've only used PBE for [EncryptedPrivateKeyInfo](https://tools.ietf.org/html/rfc5208#section-6) structure, and haven't yet seen an example with MAC.
